name: Multi-Environment Build and Deploy

on:
  workflow_dispatch:
  push:
    # Run when commits are pushed to mainline branch (main or master)
    # Set this to the mainline branch you are using
    branches:
      # - main
      # - master
      - none

permissions:
  id-token: write
  contents: read

env:
  # edit these to match the names of your environments
  dev_env: <dev_env_name>
  test_env: <test_env_name>
  prod_env: <prod_env_name>

jobs:
  deploy-dev:
    uses: ./.github/workflows/deploy-template.yml
    secrets: inherit
    with:
      AZURE_ENV_NAME: $dev_env

  deploy-test:
    uses: ./.github/workflows/deploy-template.yml
    secrets: inherit
    needs: [deploy-dev]
    with:
      AZURE_ENV_NAME: $test_env

  deploy-prod:
    uses: ./.github/workflows/deploy-template.yml
    secrets: inherit
    needs: [deploy-test]
    with:
      AZURE_ENV_NAME: $prod_env
